---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: overseerr
  namespace: bakery-media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: overseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: overseerr
    spec:
      containers:
        - name: overseerr
          env:
            - name: TZ
              value: America/Vancouver
          image: sctx/overseerr
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 5055
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 5055
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 5055
            timeoutSeconds: 1
          ports:
            - containerPort: 5055
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: overseerr-configs
              subPath: k8s-overseerr/config/
              mountPath: /app/config
      volumes:
        - name: overseerr-configs
          nfs:
            server: 10.0.0.199
            path: /run/nfs4/backup/bakery-configs
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: overseerr
  namespace: bakery-media
spec:
  type: NodePort
  ports:
    - port: 5055
      targetPort: 5055
  selector:
    app: overseerr
