---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: radarr
  namespace: bakery-media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
        - name: radarr
          env:
            - name: TZ
              value: PST
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          image: linuxserver/radarr:arm64v8-latest
          imagePullPolicy: IfNotPresent
          livenessProbe:
            tcpSocket:
              port: 7878
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 7878
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 7878
            timeoutSeconds: 1
          ports:
            - containerPort: 7878
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: radarr-plexmedia
              mountPath: /mnt/media
            - name: radarr-configs
              subPath: k8s-radarr/config/
              mountPath: /config
      volumes:
        - name: radarr-plexmedia
          nfs:
            server: 10.0.0.199
            path: /run/nfs4/cooling-rack/plex
        - name: radarr-configs
          nfs:
            server: 10.0.0.199
            path: /run/nfs4/backup/bakery-configs
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: bakery-media
spec:
  type: NodePort
  ports:
    - port: 7878
      targetPort: 7878
  selector:
    app: radarr
