---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: transmission
  namespace: bakery-media
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
        - name: transmission
          env:
            - name: TZ
              value: PST
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1003"
            - name: DOCKER_MODS
              value: "linuxserver/mods:transmission-transmissionic"
          image: linuxserver/transmission:arm64v8-latest
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 9091
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 6
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 9091
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 9091
            timeoutSeconds: 1
          ports:
            - containerPort: 9091
              name: http
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: transmission-plexmedia
              mountPath: /downloads
            - name: transmission-configs
              subPath: k8s-transmission/config/
              mountPath: /config
      volumes:
        - name: transmission-plexmedia
          nfs:
            server: 10.0.0.199
            path: /run/nfs4/cooling-rack/plex/torrents/
        - name: transmission-configs
          nfs:
            server: 10.0.0.199
            path: /run/nfs4/backup/bakery-configs
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: transmission-peer
  namespace: bakery-media
spec:
  type: NodePort
  ports:
    - port: 49153
      targetPort: 49153
      protocol: UDP
  selector:
    app: transmission

---
apiVersion: v1
kind: Service
metadata:
  name: transmission-ui
  namespace: bakery-media
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
  selector:
    app: transmission